### ISSUE TITLE
Using the Deploy to Bluemix Button, some files aren't running on strict mode.

### ISSUE THREAD

**Issue by Tomcli** [IBM/watson-multimedia-analyzer#19]
Some files in the lib/enricher didn't enable strict mode using the Deploy to Bluemix Button and create the following errors.
```
2017-09-18T10:03:00.37-0700 [APP/PROC/WEB/0] ERR /home/vcap/app/lib/enricher/index.js:32
2017-09-18T10:03:00.37-0700 [APP/PROC/WEB/0] ERR   let text = null;
2017-09-18T10:03:00.37-0700 [APP/PROC/WEB/0] ERR   ^^^
2017-09-18T10:03:00.37-0700 [APP/PROC/WEB/0] ERR SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
2017-09-18T10:03:00.37-0700 [APP/PROC/WEB/0] ERR     at exports.runInThisContext (vm.js:53:16)
2017-09-18T10:03:00.37-0700 [APP/PROC/WEB/0] ERR     at Module._compile (module.js:373:25)
2017-09-18T10:03:00.37-0700 [APP/PROC/WEB/0] ERR     at Object.Module._extensions..js (module.js:416:10)
2017-09-18T10:03:00.37-0700 [APP/PROC/WEB/0] ERR     at Module.load (module.js:343:32)
2017-09-18T10:03:00.37-0700 [APP/PROC/WEB/0] ERR     at Function.Module._load (module.js:300:12)
2017-09-18T10:03:00.37-0700 [APP/PROC/WEB/0] ERR     at Module.require (module.js:353:17)
2017-09-18T10:03:00.37-0700 [APP/PROC/WEB/0] ERR     at require (internal/module.js:12:17)
2017-09-18T10:03:00.37-0700 [APP/PROC/WEB/0] ERR     at Object.<anonymous> (/home/vcap/app/app.js:37:16)
2017-09-18T10:03:00.37-0700 [APP/PROC/WEB/0] ERR     at Module._compile (module.js:409:26)
2017-09-18T10:03:00.37-0700 [APP/PROC/WEB/0] ERR     at Object.Module._extensions..js (module.js:416:10)
```

**Comment by rhagarty** [comment]
Thanks. Will take a look.

FYI - we normally run the UI locally. The deploy to Bluemix is mostly for the convenience of creating all of the Watson services with one step. But this is definitely an issue and we will address it ASAP.

**Comment by swgraham** [comment]
So I think this is a version of Node.js issue -- I don't generate this error.  Any idea how to test this locally? My linter keeps telling me I don't need use strict :-)

**Comment by rhagarty** [comment]
Updated node version to ">= 7" and it now builds and runs without errors.
